name: 1 Steam gry scraper

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch: {}

jobs:
  specials:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run specials scraper
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          MIN_DISCOUNT: "20"
          CC: "DE"
        run: python steam_promocje_gry_load.py
